[build]
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://hostel-management-1-xwlr.onrender.com/api/:splat"
  status = 200
  force = true
